openapi: 3.0.3
info:
  description: 'The rest api of a simple compliments system, just for learning porpouses.'
  version: 1.0.0
  title: NLW Valoriza
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: victor.florencio@univem.edu.br
tags:
  - name: user
    description: Everything about the users
  - name: compliment
    description: The compliments history
  - name: tag
    description: The default tags registered
  - name: authentication
    description: System authorization
paths:
  /users:
    post:
      tags:
        - user
      summary: Creates a new user
      description: If you not authenticated yet you should register yourself
      operationId: createUser
      requestBody:
        description: Created user object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                admin:
                  type: boolean
      responses:
        '201':
          description: User was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Wrong user informations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
    get:
      tags:
        - user
      summary: List all users in the system
      description: If you are an admin user you can check all existing users in the system
      operationId: listUsers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: successful operation
  /users/compliments/send:
    get:
      tags:
        - user
      summary: List all sent compliments
      description: Will list all compliments which you have been the sender
      operationId: userSentCompliments
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compliment'
          description: successful operation
  /users/compliments/receive:
    get:
      tags:
        - user
      summary: List all received compliments
      description: Will list all compliments which you have been the receiver
      operationId: userReceivedCompliments
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Compliment'
          description: successful operation
  /compliments:
    post:
      tags:
        - compliment
      summary: Creates a new compliment
      description: If you not authenticated yet you should register yourself
      operationId: createCompliment
      requestBody:
        description: Created user object
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tag_id:
                  type: string
                user_receiver:
                  type: string
                message:
                  type: string
      responses:
        '201':
          description: Compliment was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compliment'
        '400':
          description: Incorrect user sender or user receiver don't exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /auth:
    post:
      tags:
        - authentication
      summary: Authenticates an user
      description: >-
        If you not authenticated yet you should ahthenticate getting your access
        token
      operationId: auth
      requestBody:
        description: Authenticates an user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        '400':
          description: Wrong credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
  /tags:
    post:
      tags:
        - tag
      summary: Creates a new tag
      description: You can create if you want use a new tag
      operationId: createTag
      requestBody:
        description: Tag information
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Tag was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: Tag name is invalid or already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultError'
    get:
      tags:
        - tag
      summary: List all available tags
      description: You can check it out all the tags in the system
      operationId: listTags
      responses:
        '200':
          description: List with all tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        password:
          type: string
        admin:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
    Compliment:
      type: object
      properties:
        id:
          type: string
        user_sender:
          type: string
        user_receiver:
          type: string
        tag_id:
          type: string
        message:
          type: string
        created_at:
          type: string
    Auth:
      type: object
      properties:
        token:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    DefaultError:
      type: object
      properties:
        message:
          type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
